openapi: 3.0.3
info:
  title: MATRIX TRANSPOSE
  version: 1.0.0
  description: API THAT TRANSPOSES THE MATRIX
paths:
  /api/{cols}/{rows}/{args}:
    get:
      operationId: api_retrieve
      parameters:
      - in: path
        name: args
        schema:
          type: string
        required: true
      - in: path
        name: cols
        schema:
          type: integer
        required: true
      - in: path
        name: rows
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
